// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactApp1.Server.Data;

#nullable disable

namespace ReactApp1.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422120700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("ReactApp1.Server.Models.Center", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Centers");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.CurriculumGridEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Hours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SyllabusId");

                    b.ToTable("CurriculumGridEntries");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Syllabus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CenterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("YearIntroduced")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("Syllabuses");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.SyllabusVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentMethods")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("LabHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LearningOutcomes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Literature")
                        .HasColumnType("TEXT");

                    b.Property<int>("OtherHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prerequisites")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TheoryHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SyllabusId");

                    b.ToTable("SyllabusVersions");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.CurriculumGridEntry", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Syllabus", "Syllabus")
                        .WithMany("CurriculumEntries")
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Syllabus", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId");

                    b.Navigation("Center");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.SyllabusVersion", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Syllabus", "Syllabus")
                        .WithMany("Versions")
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Syllabus", b =>
                {
                    b.Navigation("CurriculumEntries");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
