// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactApp1.Server.Data;

#nullable disable

namespace ReactApp1.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422130459_InitialSeedData")]
    partial class InitialSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("ReactApp1.Server.Models.Center", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Centers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "WI",
                            Name = "Wydział Informatyki"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "WM",
                            Name = "Wydział Matematyki"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "WF",
                            Name = "Wydział Fizyki"
                        });
                });

            modelBuilder.Entity("ReactApp1.Server.Models.CurriculumGridEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Hours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SyllabusId");

                    b.ToTable("CurriculumGridEntries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("85656f01-9193-496c-a044-2d6d0bf8a873"),
                            Hours = 60,
                            Semester = 3,
                            SyllabusId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("63078e1c-cc2c-4687-a0a7-f1f2c63f878c"),
                            Hours = 75,
                            Semester = 4,
                            SyllabusId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("aaa158b9-2f05-4435-bf15-42e4ef3985fd"),
                            Hours = 30,
                            Semester = 1,
                            SyllabusId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("b86482bc-6097-48c9-9445-6e4205986471"),
                            Hours = 15,
                            Semester = 2,
                            SyllabusId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("28d9e810-7453-40f6-9b32-30f9a27b78a1"),
                            Hours = 60,
                            Semester = 5,
                            SyllabusId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Year = 2026
                        });
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Syllabus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CenterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("YearIntroduced")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("Syllabuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CenterId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "INF-PO-001",
                            Description = "Kurs zaawansowanego programowania obiektowego w C# i .NET",
                            Title = "Programowanie Obiektowe",
                            YearIntroduced = 2025
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CenterId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "INF-BD-002",
                            Description = "Projektowanie i administracja relacyjnych baz danych",
                            Title = "Bazy Danych",
                            YearIntroduced = 2026
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CenterId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "MAT-AL-001",
                            Description = "Podstawy algebry liniowej dla studentów I stopnia",
                            Title = "Algebra Liniowa",
                            YearIntroduced = 2025
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CenterId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "FIZ-KW-001",
                            Description = "Wprowadzenie do mechaniki kwantowej",
                            Title = "Fizyka Kwantowa",
                            YearIntroduced = 2026
                        });
                });

            modelBuilder.Entity("ReactApp1.Server.Models.SyllabusVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentMethods")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("LabHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LearningOutcomes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Literature")
                        .HasColumnType("TEXT");

                    b.Property<int>("OtherHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prerequisites")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TheoryHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SyllabusId");

                    b.ToTable("SyllabusVersions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            AssessmentMethods = "Projekt końcowy (60%), Kolokwium (40%)",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "dr Jan Kowalski",
                            Description = "Podstawy OOP, dziedziczenie, polimorfizm, wzorce projektowe",
                            LabHours = 30,
                            LearningOutcomes = "Student zna zasady SOLID, umie stosować wzorce projektowe",
                            Literature = "Clean Code - Robert Martin, Design Patterns - Gang of Four",
                            OtherHours = 0,
                            Prerequisites = "Podstawy programowania",
                            SyllabusId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            TheoryHours = 30,
                            Title = "Programowanie Obiektowe",
                            TotalHours = 60,
                            VersionNumber = 1
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000001"),
                            AssessmentMethods = "Egzamin pisemny (50%), Projekt (50%)",
                            CreatedAt = new DateTime(2026, 2, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "dr Anna Nowak",
                            Description = "SQL, normalizacja, indeksy, transakcje, administracja",
                            LabHours = 45,
                            LearningOutcomes = "Student umie projektować schematy baz danych, pisać zaawansowane zapytania SQL",
                            Literature = "Database System Concepts - Silberschatz, SQL dla każdego",
                            OtherHours = 0,
                            Prerequisites = "Podstawy informatyki",
                            SyllabusId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            TheoryHours = 30,
                            Title = "Bazy Danych",
                            TotalHours = 75,
                            VersionNumber = 1
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000001"),
                            AssessmentMethods = "Egzamin (70%), Kolokwia (30%)",
                            CreatedAt = new DateTime(2025, 3, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "prof. Marek Wiśniewski",
                            Description = "Przestrzenie wektorowe, macierze, układy równań, wartości własne",
                            LabHours = 15,
                            LearningOutcomes = "Student rozumie podstawowe struktury algebry liniowej",
                            Literature = "Algebra liniowa - G. Banaszak, Linear Algebra - Lay",
                            OtherHours = 0,
                            Prerequisites = "Matematyka szkolna",
                            SyllabusId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            TheoryHours = 30,
                            Title = "Algebra Liniowa",
                            TotalHours = 45,
                            VersionNumber = 1
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000001"),
                            AssessmentMethods = "Egzamin ustny (60%), Zadania domowe (40%)",
                            CreatedAt = new DateTime(2026, 4, 12, 11, 15, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "prof. Ewa Zielińska",
                            Description = "Postulaty mechaniki kwantowej, funkcja falowa, operator Hamiltona",
                            LabHours = 0,
                            LearningOutcomes = "Student rozumie podstawowe pojęcia mechaniki kwantowej",
                            Literature = "Introduction to Quantum Mechanics - Griffiths",
                            OtherHours = 15,
                            Prerequisites = "Fizyka klasyczna, Matematyka wyższa",
                            SyllabusId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            TheoryHours = 45,
                            Title = "Fizyka Kwantowa",
                            TotalHours = 60,
                            VersionNumber = 1
                        });
                });

            modelBuilder.Entity("ReactApp1.Server.Models.CurriculumGridEntry", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Syllabus", "Syllabus")
                        .WithMany("CurriculumEntries")
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Syllabus", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId");

                    b.Navigation("Center");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.SyllabusVersion", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Syllabus", "Syllabus")
                        .WithMany("Versions")
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Syllabus", b =>
                {
                    b.Navigation("CurriculumEntries");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
