// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactApp1.Server.Data;

#nullable disable

namespace ReactApp1.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428183614_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-reader-guid",
                            Name = "Reader",
                            NormalizedName = "READER"
                        },
                        new
                        {
                            Id = "role-editor-guid",
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "role-admin-guid",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-editor-guid",
                            RoleId = "role-editor-guid"
                        },
                        new
                        {
                            UserId = "user-reader-guid",
                            RoleId = "role-reader-guid"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ReactApp1.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CenterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-editor-guid",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "38b9fb20-442b-4103-82b3-492058c02b63",
                            CreatedAt = new DateTime(2026, 4, 28, 18, 36, 14, 145, DateTimeKind.Utc).AddTicks(1540),
                            Email = "editor@uczelnia.pl",
                            EmailConfirmed = true,
                            FullName = "Jan Kowalski (Edytor)",
                            LockoutEnabled = false,
                            NormalizedEmail = "EDITOR@UCZELNIA.PL",
                            NormalizedUserName = "EDITOR@UCZELNIA.PL",
                            PasswordHash = "AQAAAAIAAYagAAAAEMD14hKZRD6hC5/nia5t0Ob7KyU+c74lc1CSG6idZM5SJStP9d3LhogSaJg+4nn8iA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "abc56447-4e57-4b35-bd06-30d6f3607116",
                            TwoFactorEnabled = false,
                            UserName = "editor@uczelnia.pl"
                        },
                        new
                        {
                            Id = "user-reader-guid",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d3237838-068f-44bb-b944-ab9fd8fa2e53",
                            CreatedAt = new DateTime(2026, 4, 28, 18, 36, 14, 180, DateTimeKind.Utc).AddTicks(2698),
                            Email = "reader@uczelnia.pl",
                            EmailConfirmed = true,
                            FullName = "Anna Nowak (Czytelnik)",
                            LockoutEnabled = false,
                            NormalizedEmail = "READER@UCZELNIA.PL",
                            NormalizedUserName = "READER@UCZELNIA.PL",
                            PasswordHash = "AQAAAAIAAYagAAAAEBWHSfiSuNMCvodistLFn25hCxDnbirqPGKVzYhmjnPa9G6vMXu6Uc31lJMq7Kho0Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0ebd6acc-f725-4f2e-992c-96dc4815e9d4",
                            TwoFactorEnabled = false,
                            UserName = "reader@uczelnia.pl"
                        });
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Center", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Centers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "WI",
                            Name = "Wydział Informatyki"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "WM",
                            Name = "Wydział Matematyki"
                        });
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Curriculum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CenterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyMode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("Curriculums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            AcademicYear = 2025,
                            CenterId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "INF-I-2025",
                            CreatedAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Program studiów pierwszego stopnia na kierunku Informatyka, rok akademicki 2025/2026",
                            Level = "I stopień",
                            Name = "Informatyka I stopień 2025/2026",
                            StudyMode = "Stacjonarne"
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            AcademicYear = 2025,
                            CenterId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "MAT-I-2025",
                            CreatedAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Description = "Program studiów pierwszego stopnia na kierunku Matematyka",
                            Level = "I stopień",
                            Name = "Matematyka I stopień 2025/2026",
                            StudyMode = "Stacjonarne"
                        });
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurriculumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EctsPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Code = "INF-PO-001",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            CurriculumId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Description = "Kurs zaawansowanego programowania obiektowego w C# i .NET",
                            EctsPoints = 6,
                            Name = "Programowanie Obiektowe",
                            Semester = 3,
                            SubjectType = "Obowiązkowy"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Code = "INF-BD-002",
                            CreatedAt = new DateTime(2025, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            CurriculumId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Description = "Projektowanie i administracja relacyjnych baz danych",
                            EctsPoints = 5,
                            Name = "Bazy Danych",
                            Semester = 4,
                            SubjectType = "Obowiązkowy"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Code = "MAT-AL-001",
                            CreatedAt = new DateTime(2025, 1, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            CurriculumId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Description = "Podstawy algebry liniowej",
                            EctsPoints = 4,
                            Name = "Algebra Liniowa",
                            Semester = 1,
                            SubjectType = "Obowiązkowy"
                        });
                });

            modelBuilder.Entity("ReactApp1.Server.Models.SubjectVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentMethods")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("LabHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LearningOutcomes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Literature")
                        .HasColumnType("TEXT");

                    b.Property<int>("OtherHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prerequisites")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TheoryHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectVersions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AssessmentMethods = "Projekt końcowy (60%), Kolokwium (40%)",
                            CreatedAt = new DateTime(2025, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "dr Jan Kowalski",
                            Description = "Podstawy OOP, dziedziczenie, polimorfizm, wzorce projektowe",
                            LabHours = 30,
                            LearningOutcomes = "Student zna zasady SOLID, umie stosować wzorce projektowe",
                            Literature = "Clean Code - Robert Martin, Design Patterns - Gang of Four",
                            OtherHours = 0,
                            Prerequisites = "Podstawy programowania",
                            SubjectId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            TheoryHours = 30,
                            Title = "Programowanie Obiektowe",
                            TotalHours = 60,
                            VersionNumber = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AssessmentMethods = "Egzamin pisemny (50%), Projekt (50%)",
                            CreatedAt = new DateTime(2025, 2, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "dr Anna Nowak",
                            Description = "SQL, normalizacja, indeksy, transakcje",
                            LabHours = 45,
                            LearningOutcomes = "Student umie projektować schematy baz danych, pisać zaawansowane zapytania SQL",
                            Literature = "Database System Concepts - Silberschatz",
                            OtherHours = 0,
                            Prerequisites = "Podstawy informatyki",
                            SubjectId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            TheoryHours = 30,
                            Title = "Bazy Danych",
                            TotalHours = 75,
                            VersionNumber = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-cccc-cccc-cccccccccccc"),
                            AssessmentMethods = "Egzamin (70%), Kolokwia (30%)",
                            CreatedAt = new DateTime(2025, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "prof. Marek Wiśniewski",
                            Description = "Przestrzenie wektorowe, macierze",
                            LabHours = 15,
                            LearningOutcomes = "Student rozumie podstawowe struktury algebry liniowej",
                            Literature = "Algebra liniowa - G. Banaszak",
                            OtherHours = 0,
                            Prerequisites = "Matematyka szkolna",
                            SubjectId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            TheoryHours = 30,
                            Title = "Algebra Liniowa",
                            TotalHours = 45,
                            VersionNumber = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactApp1.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReactApp1.Server.Models.ApplicationUser", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Center");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Curriculum", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Center");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Subject", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Curriculum", "Curriculum")
                        .WithMany("Subjects")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.SubjectVersion", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.Subject", "Subject")
                        .WithMany("Versions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Curriculum", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.Subject", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
